version: '2.1'

services:
  auth:
    build:
      context: .
      dockerfile: auth.Dockerfile
    image: auth
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./data/:/data
